let assets=[];
const euro=n=>"€"+Number(n||0).toLocaleString();
function normalize(a){return {id:a.court_id,model:[a.manufacturer,a.model].filter(Boolean).join(' '),country:a.country,year:a.year_installed,grade:a.grade||'—',type:a.type||'—',glass:a.glass_thickness_mm?`${a.glass_thickness_mm} mm tempered`:'Specification pending',features:a.description||'Inspection pending',price:Number(a.asking_price_eur||0),status:a.status};}
async function loadAssets(){try{const r=await fetch('/api/assets',{cache:'no-store'});const body=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status}: ${body.slice(0,180)}`);let data;try{data=JSON.parse(body)}catch{throw new Error(`Invalid API response: ${body.slice(0,180)}`)}assets=data.map(normalize);render()}catch(e){assets=[];render();showToast(`Database/API error: ${e.message}`)}}
function render(){const q=(document.getElementById('search').value||'').toLowerCase(),g=document.getElementById('grade').value,t=document.getElementById('type').value;const list=assets.filter(a=>(!q||`${a.model} ${a.country} ${a.id}`.toLowerCase().includes(q))&&(!g||a.grade===g)&&(!t||a.type===t));document.getElementById('cards').innerHTML=list.length?list.map(a=>`<article class="card"><div class="thumb"><span>${a.id}</span></div><div class="cardbody"><div class="topline"><div class="eyebrow">${a.country} · ${a.year||'Year n/a'}</div><span class="grade">${a.grade}</span></div><h3>${a.model}</h3><div class="meta">${a.type} · ${a.glass}<br>${a.features}</div><div class="cardfoot"><b>${euro(a.price)}</b><button onclick="openListing('${a.id}')">View asset</button></div></div></article>`).join(''):`<div style="grid-column:1/-1;padding:30px;background:#fff;border:1px solid #dce3da;border-radius:12px">No published courts found. Add inventory in Supabase to make the marketplace live.</div>`}
function openListing(id){const a=assets.find(x=>x.id===id);if(!a)return;document.getElementById('listingContent').innerHTML=`<div class="eyebrow">${a.id} · NOWO GRADE ${a.grade}</div><h2>${a.model}</h2><p><b>${a.country}</b> · ${a.year||'Year n/a'} · ${a.type}</p><hr><p><b>Glass:</b> ${a.glass}<br><b>Features:</b> ${a.features}<br><b>FIP status:</b> Verification required before any certification claim.</p><h3>${euro(a.price)}</h3><button class="limebtn wide" onclick="requestAsset('${a.id}')">Request asset</button>`;openModal('listingModal')}
async function requestAsset(id){const buyer=prompt('Your company / name');if(!buyer)return;const email=prompt('Your email');if(!email)return;const message=prompt('Message (optional)')||'';try{const r=await fetch('/api/inquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({court_id:id,buyer_company:buyer,buyer_email:email,message})});if(!r.ok){const t=await r.text();throw new Error(t.slice(0,140))}closeModal('listingModal');showToast('Inquiry sent.')}catch(e){showToast(`Inquiry failed: ${e.message}`)}}
function calculate(){const n=+document.getElementById('newPrice').value||18000,a=+document.getElementById('age').value||0,m=+document.getElementById('cond').value,factor=Math.max(.45,1-a*.09),mid=Math.round(n*factor*m/100)*100;document.getElementById('estimate').textContent=`${euro(Math.round(mid*.9))}–${euro(Math.round(mid*1.1))}`}
async function submitSell(e){e.preventDefault();const fd=new FormData(e.target),request=Object.fromEntries(fd.entries());try{const r=await fetch('/api/sellers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)});const text=await r.text();if(!r.ok)throw new Error(text.slice(0,220));e.target.reset();showToast('Court details received. We will review the asset before publishing.')}catch(err){showToast(`Submission failed: ${err.message}`)}}
function openModal(id){document.getElementById(id).style.display='flex'}function closeModal(id){document.getElementById(id).style.display='none'}function scrollToId(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',7000)}
// iPhone: prevent horizontal document movement and immediately return the viewport to x=0 if the browser reports any horizontal scroll.
(function lockHorizontalTouch(){let sx=0,sy=0;const resetX=()=>{if(window.scrollX!==0||document.documentElement.scrollLeft!==0||document.body.scrollLeft!==0)window.scrollTo(0,window.scrollY)};document.addEventListener('touchstart',e=>{const t=e.touches[0];sx=t.clientX;sy=t.clientY},{passive:true});document.addEventListener('touchmove',e=>{const t=e.touches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>Math.abs(dy)+4){e.preventDefault();resetX()}},{passive:false});window.addEventListener('scroll',resetX,{passive:true});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});resetX()})();
window.addEventListener('click',e=>{if(e.target.classList.contains('modal'))e.target.style.display='none'});loadAssets();