document.addEventListener('DOMContentLoaded',()=>{
 const sell=document.getElementById('sell');
 if(!sell)return;
 const section=document.createElement('section');section.id='demand';section.className='section lead-section';section.innerHTML=`<div class="lead-intro"><div class="eyebrow">BUILD THE DEMAND NETWORK</div><h2>Can't find the right court?</h2><p>Tell PADEL TRADE what you need. We can match your request with verified courts and sellers as inventory comes online.</p></div><form class="lead-form" onsubmit="submitBuyerRequest(event)"><h3>Find me a court</h3><div class="row"><input required name="country" placeholder="Country"><input name="city" placeholder="City / region"></div><div class="row"><input required name="court_count" type="number" min="1" placeholder="Number of courts"><input name="budget_eur" type="number" min="0" placeholder="Budget per court €"></div><div class="row"><select name="indoor_outdoor"><option value="">Indoor / outdoor</option><option>Indoor</option><option>Outdoor</option><option>Either</option></select><select name="condition"><option value="">Condition</option><option>New</option><option>Excellent</option><option>Good</option><option>Needs refurbishment</option></select></div><div class="row"><input name="preferred_manufacturer" placeholder="Preferred manufacturer"><input name="needed_by" type="date"></div><label class="check"><input name="transport_installation" type="checkbox" value="true"> I may need transport / installation</label><textarea name="details" placeholder="Tell us anything important: location, timeline, specifications, dismantling, glass, turf, etc."></textarea><div class="row"><input name="name" placeholder="Name / company"><input required name="email" type="email" placeholder="Email"></div><button class="limebtn wide">Send my requirement</button><small>We will contact you when a relevant opportunity appears. No spam.</small></form>`;
 sell.parentNode.insertBefore(section,sell);
 const services=document.getElementById('services');
 const service=document.createElement('section');service.className='section service-leads';service.innerHTML=`<div class="eyebrow">INFRASTRUCTURE SERVICES</div><h2>Need help moving a court?</h2><div class="servicegrid service-lead-grid">${['Inspection','Dismantling','Transport','Refurbishment','Installation','Club liquidation'].map((x,i)=>`<button class="service-tile" onclick="openServiceRequest('${x}')"><b>0${i+1}</b><h3>${x}</h3><span>Request service →</span></button>`).join('')}</div>`;
 services.parentNode.insertBefore(service,services.nextSibling);
});
function submitBuyerRequest(e){e.preventDefault();const f=e.target,b=Object.fromEntries(new FormData(f).entries());fetch('/api/buyer-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}).then(async r=>{const t=await r.text();if(!r.ok)throw new Error(t.slice(0,160));f.reset();showToast('Requirement received. We will look for a match.')}).catch(err=>showToast('Request failed: '+err.message))}
function openServiceRequest(service){document.getElementById('serviceModalContent').innerHTML=`<h2>${service}</h2><p>Tell us where and what you need. We will match you with the right operator.</p><form onsubmit="submitServiceRequest(event)"><input required name="service" type="hidden" value="${service}"><input name="name" placeholder="Name / company"><input required name="country" placeholder="Country"><input name="city" placeholder="City / region"><input name="court_count" type="number" min="1" placeholder="Number of courts"><input required name="email" type="email" placeholder="Email"><textarea name="details" placeholder="What do you need?"></textarea><button class="limebtn wide">Request service</button></form>`;openModal('serviceModal')}
function submitServiceRequest(e){e.preventDefault();const f=e.target,b=Object.fromEntries(new FormData(f).entries());fetch('/api/service-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}).then(async r=>{const t=await r.text();if(!r.ok)throw new Error(t.slice(0,160));closeModal('serviceModal');showToast('Service request received.')}).catch(err=>showToast('Request failed: '+err.message))}
